version: '3'

services:
  db:
    image: postgres:15
    container_name: weather-db
    environment:
      POSTGRES_USER: yassine236589
      POSTGRES_PASSWORD: yassine986532
      POSTGRES_DB: weather_data
    ports:
      - "5432:5432"             
    volumes:
      - pgdata:/var/lib/postgresql/data